/**
 * ipc.ts — THE CONTRACT between the React UI and the Tauri (Rust) backend.
 *
 * ⚠️ CODEX: This file is the source of truth. Implement every command and
 * event listed here, with exactly these names and payload shapes, using
 * Tauri v2 `#[tauri::command]` handlers. Do NOT rename anything here;
 * change the Rust side to match this file, never the other way around.
 *
 * When running outside Tauri (plain `npm run dev` in a browser) this module
 * falls back to an in-memory mock so the UI is fully demoable.
 */

import { isWindows } from "./platform";

// ---------- Types ----------

export type ShareStatus = "stopped" | "starting" | "live" | "error";

export interface ShareStats {
  visitors: number; // unique remote IPs since started
  requests: number; // total HTTP requests since started
  bytesServed: number; // total bytes since started
}

export type ProviderKind =
  | "cloudflareQuick"
  | "cloudflareManaged"
  | "ngrok"
  | "custom";

export interface ProviderProfile {
  id: string;
  name: string;
  kind: ProviderKind;
  executable?: string;
  arguments: string[];
  publicUrl?: string;
  urlPattern?: string;
  credentialEnv?: string;
  forwardedIpHeader?: string;
  localPort?: number;
  createdAt: string;
  builtIn: boolean;
  credentialConfigured: boolean;
}

export interface SaveProviderProfileInput {
  id?: string;
  name: string;
  kind: Exclude<ProviderKind, "cloudflareQuick">;
  executable?: string;
  arguments: string[];
  publicUrl?: string;
  urlPattern?: string;
  credentialEnv?: string;
  forwardedIpHeader?: string;
  localPort?: number;
  credential?: string;
  clearCredential?: boolean;
}

export interface ProviderTestResult {
  url: string;
  message: string;
}

export interface Share {
  id: string; // uuid v4, generated by backend
  kind: "folder" | "port";
  name: string; // display name, defaults to folder basename
  path: string | null; // absolute path (kind=folder)
  port: number | null; // local port (kind=port)
  url: string | null; // provider-supplied public HTTPS URL when live
  status: ShareStatus;
  error: string | null; // human-readable, set when status=error
  passwordProtected: boolean; // basic-auth on the local server
  showListing: boolean; // serve directory index pages (folder shares)
  allowUploads: boolean; // accept uploads into the folder (folder shares)
  autoStart: boolean; // start this share when the app launches
  providerId?: string | null; // null/absent = inherit the global default
  stats: ShareStats;
  createdAt: string; // ISO 8601
}

export interface CreateShareInput {
  kind: "folder" | "port";
  path?: string; // required when kind=folder
  port?: number; // required when kind=port
  name?: string;
  password?: string; // plaintext, backend stores in the OS credential store
  showListing?: boolean; // default true
  allowUploads?: boolean; // default false
  autoStart?: boolean; // default false
  startNow?: boolean; // default true
  providerId?: string; // omitted = inherit the global default
}

export interface UpdateShareInput {
  name?: string;
  password?: string | null; // null clears the password
  showListing?: boolean;
  allowUploads?: boolean;
  autoStart?: boolean;
  providerId?: string | null; // null = return to the global default
}

export interface Settings {
  launchAtLogin: boolean; // register/unregister OS login item
  autoStartShares: boolean; // master switch: honor per-share autoStart
  showDockIcon: boolean; // false = tray-only app; persisted name retained for compatibility
  notifyOnFirstVisitor: boolean; // native notification on first visit
  copyUrlOnStart: boolean; // auto-copy public URL to clipboard when live
  theme: "system" | "light" | "dark";
  defaultProviderId: string;
}

export type AppEvent =
  | { type: "share_changed"; share: Share } // any status/url/field change
  | { type: "share_removed"; id: string }
  | { type: "stats_updated"; id: string; stats: ShareStats };

// ---------- Commands (Codex: implement each as #[tauri::command]) ----------

export interface Ipc {
  /** Return all shares, persisted across launches (store in app-data JSON). */
  listShares(): Promise<Share[]>;
  /** Create a share. If startNow (default), begin tunnel immediately. */
  createShare(input: CreateShareInput): Promise<Share>;
  /** Start serving + tunneling. Resolves once status is "starting"; the
   *  "live" transition (with URL) arrives via a share_changed event. */
  startShare(id: string): Promise<void>;
  /** Stop the tunnel and local server. */
  stopShare(id: string): Promise<void>;
  /** Stop (if running) and remove permanently. */
  deleteShare(id: string): Promise<void>;
  /** Patch mutable fields. If the share is live, restart it transparently. */
  updateShare(id: string, patch: UpdateShareInput): Promise<Share>;
  /** Open the native folder picker. Resolves null if the user cancels. */
  pickFolder(): Promise<string | null>;
  /** Reveal the shared folder in the platform file manager. */
  revealInFinder(path: string): Promise<void>;
  /** Open a URL in the user's default browser. */
  openUrl(url: string): Promise<void>;
  getSettings(): Promise<Settings>;
  updateSettings(patch: Partial<Settings>): Promise<Settings>;
  listProviderProfiles(): Promise<ProviderProfile[]>;
  saveProviderProfile(input: SaveProviderProfileInput): Promise<ProviderProfile>;
  deleteProviderProfile(id: string): Promise<void>;
  testProvider(id: string): Promise<ProviderTestResult>;
  pickProviderExecutable(): Promise<string | null>;
  /** Subscribe to backend events. Returns an unsubscribe fn. */
  onEvent(cb: (e: AppEvent) => void): () => void;
}

// ---------- Runtime: Tauri bridge with browser-mock fallback ----------

const isTauri =
  typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;

function tauriIpc(): Ipc {
  // Lazy imports so the browser build doesn't need @tauri-apps/api resolved.
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const core = (window as any).__TAURI__?.core ?? null;
  const event = (window as any).__TAURI__?.event ?? null;
  const invoke = (cmd: string, args?: any) =>
    core
      ? core.invoke(cmd, args)
      : import("@tauri-apps/api/core").then((m) => m.invoke(cmd, args));

  return {
    listShares: () => invoke("list_shares"),
    createShare: (input) => invoke("create_share", { input }),
    startShare: (id) => invoke("start_share", { id }),
    stopShare: (id) => invoke("stop_share", { id }),
    deleteShare: (id) => invoke("delete_share", { id }),
    updateShare: (id, patch) => invoke("update_share", { id, patch }),
    pickFolder: () => invoke("pick_folder"),
    revealInFinder: (path) => invoke("reveal_in_finder", { path }),
    openUrl: (url) => invoke("open_url", { url }),
    getSettings: () => invoke("get_settings"),
    updateSettings: (patch) => invoke("update_settings", { patch }),
    listProviderProfiles: () => invoke("list_provider_profiles"),
    saveProviderProfile: (input) => invoke("save_provider_profile", { input }),
    deleteProviderProfile: (id) => invoke("delete_provider_profile", { id }),
    testProvider: (id) => invoke("test_provider", { id }),
    pickProviderExecutable: () => invoke("pick_provider_executable"),
    onEvent: (cb) => {
      let unlisten: (() => void) | null = null;
      const p = event
        ? event.listen("app_event", (e: any) => cb(e.payload))
        : import("@tauri-apps/api/event").then((m) =>
            m.listen("app_event", (e: any) => cb(e.payload)),
          );
      Promise.resolve(p).then((u: any) => (unlisten = u));
      return () => unlisten?.();
    },
  };
}

// ---------- Browser mock (UI demo without Tauri) ----------

function mockIpc(): Ipc {
  const listeners = new Set<(e: AppEvent) => void>();
  const emit = (e: AppEvent) => listeners.forEach((l) => l(e));
  const uuid = () => Math.random().toString(36).slice(2, 10);
  const words = ["mango", "harbor", "violet", "comet", "birch", "lagoon"];
  const fakeUrl = () =>
    `https://${words[Math.floor(Math.random() * words.length)]}-${uuid()}.trycloudflare.com`;

  let settings: Settings = {
    launchAtLogin: false,
    autoStartShares: true,
    showDockIcon: true,
    notifyOnFirstVisitor: true,
    copyUrlOnStart: true,
    theme: "system",
    defaultProviderId: "cloudflare-quick",
  };

  const providerProfiles: ProviderProfile[] = [
    {
      id: "cloudflare-quick",
      name: "Cloudflare Quick Tunnel",
      kind: "cloudflareQuick",
      arguments: [],
      forwardedIpHeader: "CF-Connecting-IP",
      createdAt: "built-in",
      builtIn: true,
      credentialConfigured: true,
    },
    {
      id: "demo-ngrok",
      name: "My ngrok",
      kind: "ngrok",
      executable: isWindows ? "C:\\Tools\\ngrok.exe" : "/usr/local/bin/ngrok",
      arguments: [],
      createdAt: new Date().toISOString(),
      builtIn: false,
      credentialConfigured: true,
    },
  ];

  const shares: Share[] = [
    {
      id: uuid(),
      kind: "folder",
      name: "Client Mockups",
      path: "/Users/tanzir/Desktop/client-mockups",
      port: null,
      url: fakeUrl(),
      status: "live",
      error: null,
      passwordProtected: true,
      showListing: true,
      allowUploads: false,
      autoStart: true,
      providerId: null,
      stats: { visitors: 4, requests: 132, bytesServed: 48_200_000 },
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: uuid(),
      kind: "folder",
      name: "portfolio-site",
      path: "/Users/tanzir/Sites/portfolio",
      port: null,
      url: null,
      status: "stopped",
      error: null,
      passwordProtected: false,
      showListing: false,
      allowUploads: false,
      autoStart: false,
      providerId: "demo-ngrok",
      stats: { visitors: 0, requests: 0, bytesServed: 0 },
      createdAt: new Date().toISOString(),
    },
  ];

  const find = (id: string) => {
    const s = shares.find((x) => x.id === id);
    if (!s) throw new Error("share not found");
    return s;
  };

  return {
    listShares: async () => structuredClone(shares),
    createShare: async (input) => {
      const share: Share = {
        id: uuid(),
        kind: input.kind,
        name:
          input.name ||
          (input.path ? input.path.split(/[\\/]/).filter(Boolean).pop()! : `Port ${input.port}`),
        path: input.path ?? null,
        port: input.port ?? null,
        url: null,
        status: "stopped",
        error: null,
        passwordProtected: !!input.password,
        showListing: input.showListing ?? true,
        allowUploads: input.allowUploads ?? false,
        autoStart: input.autoStart ?? false,
        providerId: input.providerId ?? null,
        stats: { visitors: 0, requests: 0, bytesServed: 0 },
        createdAt: new Date().toISOString(),
      };
      shares.unshift(share);
      if (input.startNow !== false) {
        setTimeout(() => this_start(share.id), 50);
      }
      return structuredClone(share);
    },
    startShare: async (id) => this_start(id),
    stopShare: async (id) => {
      const s = find(id);
      s.status = "stopped";
      s.url = null;
      emit({ type: "share_changed", share: structuredClone(s) });
    },
    deleteShare: async (id) => {
      const i = shares.findIndex((x) => x.id === id);
      if (i >= 0) shares.splice(i, 1);
      emit({ type: "share_removed", id });
    },
    updateShare: async (id, patch) => {
      const s = find(id);
      if (patch.name !== undefined) s.name = patch.name;
      if (patch.password !== undefined) s.passwordProtected = !!patch.password;
      if (patch.showListing !== undefined) s.showListing = patch.showListing;
      if (patch.allowUploads !== undefined) s.allowUploads = patch.allowUploads;
      if (patch.autoStart !== undefined) s.autoStart = patch.autoStart;
      if (patch.providerId !== undefined) s.providerId = patch.providerId;
      emit({ type: "share_changed", share: structuredClone(s) });
      return structuredClone(s);
    },
    pickFolder: async () => "/Users/tanzir/Desktop/example-folder",
    revealInFinder: async () => {},
    openUrl: async (url) => { window.open(url, "_blank"); },
    getSettings: async () => ({ ...settings }),
    updateSettings: async (patch) => {
      settings = { ...settings, ...patch };
      return { ...settings };
    },
    listProviderProfiles: async () => structuredClone(providerProfiles),
    saveProviderProfile: async (input) => {
      const existing = input.id
        ? providerProfiles.find((profile) => profile.id === input.id)
        : undefined;
      const profile: ProviderProfile = {
        id: existing?.id ?? uuid(),
        name: input.name,
        kind: input.kind,
        executable: input.executable,
        arguments: [...input.arguments],
        publicUrl: input.publicUrl,
        urlPattern: input.urlPattern,
        credentialEnv: input.credentialEnv,
        forwardedIpHeader: input.forwardedIpHeader,
        localPort: input.localPort,
        createdAt: existing?.createdAt ?? new Date().toISOString(),
        builtIn: false,
        credentialConfigured:
          input.clearCredential ? false : !!input.credential || existing?.credentialConfigured || false,
      };
      if (existing) Object.assign(existing, profile);
      else providerProfiles.push(profile);
      return structuredClone(profile);
    },
    deleteProviderProfile: async (id) => {
      const index = providerProfiles.findIndex((profile) => profile.id === id);
      if (index >= 0) providerProfiles.splice(index, 1);
    },
    testProvider: async (id) => {
      const profile = providerProfiles.find((candidate) => candidate.id === id);
      if (!profile) throw new Error("provider not found");
      const url = profile.publicUrl
        ?? (profile.kind === "ngrok"
          ? `https://${uuid()}.ngrok-free.app`
          : fakeUrl());
      return { url, message: `${profile.name} connected successfully.` };
    },
    pickProviderExecutable: async () =>
      isWindows ? "C:\\Tools\\vendor-tunnel.exe" : "/usr/local/bin/vendor-tunnel",
    onEvent: (cb) => {
      listeners.add(cb);
      return () => listeners.delete(cb);
    },
  };

  function this_start(id: string) {
    const s = find(id);
    s.status = "starting";
    s.url = null;
    emit({ type: "share_changed", share: structuredClone(s) });
    setTimeout(() => {
      s.status = "live";
      s.url = fakeUrl();
      emit({ type: "share_changed", share: structuredClone(s) });
    }, 1400);
  }
}

export const ipc: Ipc = isTauri ? tauriIpc() : mockIpc();
